version: "3.9"

services:

  innotter_db:
    image: postgres:12.15
    restart: always
    container_name: innotter_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5436"
  innotter_project:
    build: .
    image: innotter:latest
    container_name: innotter
    volumes:
      - .:/app
    depends_on:
      - innotter_db
    env_file:
      - .env
    ports:
      - "8000:8080"