# Generated by Django 4.2.3 on 2023-08-09 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_alter_page_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=[], related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
